---
# tasks file for common/fedora
- name: Install RPM Fusion (free)
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
- name: Install RPM Fusion (nonfree)
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present

- name: Create home directories
  file:
    path: "/home/{{ primary_user }}/{{ item }}"
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  with_items:
    - .icons
    - .themes
    - bin
    - nginx
    - projects

- name: Install simple programs
  dnf: name={{ item }} state=present
  with_items:
    - '@Development Tools'
    - ansible
    - bzr
    - cloc
    - dmidecode
    - dnf-plugins-core
    - filezilla
    - gcc-c++
    - gnome-terminal-nautilus
    - gnome-tweak-tool
    - gstreamer
    - gstreamer-plugins-base
    - htop
    - libselinux-python
    - mycli
    - nano
    - pv
    - python2-mysql
    - python-docker
    - python3-mysql
    - redhat-rpm-config
    - ruby
    - ruby-devel
    - snapd
    - sqlite
    - sqlite-devel
    - sysfsutils
    - terminator
    - vim
    - vim-powerline
    - vlc

- name: Get system product name
  shell: "dmidecode -s system-product-name"
  changed_when: false
  register: system_product_name

- set_fact:
    system_is_macmini: true
  when: system_product_name|lower is search("macmini")

- name: Create snap symlink
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Disable selinux
  selinux: state=disabled
  when: disable_selinux

- name: Disable ipv6
  template: src=templates/sysctl/99-ipv6.conf dest=/etc/sysctl.d/99-ipv6.conf
  notify:
    - sysctl
  when: disable_ipv6

- name: Set max_user_watches
  template: src=templates/idea/idea.conf dest=/etc/sysctl.d/idea.conf
  notify:
    - sysctl

- name: Install vagrant
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - vagrant-sshfs
  when: install_vagrant

- name: Install openjdk
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - java
    - java-devel
  when: install_openjdk

- name: Install mariadb/mysql
  include_tasks: fedora/mysql.yml
  tags: mariadb mysql

- name: Install redis
  block:
    - name: Install redis
      dnf: name=redis state=present
    - name: Start redis service
      systemd: name=redis enabled=true state=started

- name: Include fedora/mailcatcher
  include_tasks: fedora/mailcatcher.yml
  tags: mailcatcher

- name: Install php
  include_tasks: fedora/php.yml
  tags: php

- name: Install nginx
  include_tasks: fedora/nginx.yml
  tags: nginx

- name: Install Node.js
  include_tasks: fedora/node.yml
  tags: node

- name: Install awscli
  include_tasks: fedora/aws.yml
  when: install_aws
  tags: aws awscli

- name: Install Docker repository
  template: src=templates/docker/docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo
  when: install_docker
- name: Check if docker could be installed
  command: "dnf search docker-ce"
  register: dnf_search_docker
  changed_when: false
  when: install_docker
- name: Install Docker
  dnf: name=docker-ce state=present
  when: install_docker and dnf_search_docker.stdout_lines|length > 2
- name: Run docker service
  systemd: name=docker enabled=true state=started
  when: install_docker and dnf_search_docker.stdout_lines|length > 2
- name: Add primary user to docker group
  user: name={{ primary_user }} groups=docker append=true
  when: install_docker and dnf_search_docker.stdout_lines|length > 2

- name: Install Google Chrome repository
  copy:
    src: files/google-chrome/google-chrome.repo
    dest: /etc/yum.repos.d/google-chrome.repo
  when: install_chrome
- name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: present
  when: install_chrome
- name: Install Chrome GNOME Shell integration
  dnf: name=chrome-gnome-shell state=present
  when: install_chrome

- name: Install Macmini wireless driver
  dnf:
    name: broadcom-wl
    state: present
  when: system_is_macmini

- name: Init /etc/sysfs.d
  file:
    path: /etc/sysfs.d
    state: directory

- name: Set sleep mode to deep
  copy:
    content: deep
    dest: /etc/sysfs.d/mem_sleep.conf

- name: Reverse Apple keyboard fn keys
  copy:
    content: options hid_apple fnmode=2
    dest: /etc/modprobe.d/hid_apple.conf
  when: reverse_apple_keyboard_fn_keys

- name: Regenerate initramfs
  shell: "dracut --regenerate-all --force"
  when: reverse_apple_keyboard_fn_keys

- name: Install Nvidia drivers
  dnf: name={{ item }} state=present
  with_items:
    - xorg-x11-drv-nvidia
    - akmod-nvidia
  when: install_nvidia_drivers

- name: Install Steam
  dnf: name=steam state=present
  when: install_steam

- name: Install Owncloud
  dnf: name={{ item }} state=present
  with_items:
    - owncloud-client
    - owncloud-client-nautilus
  when: install_owncloud_client

- name: Import Atom gpgkey
  rpm_key:
    key: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present
  when: install_atom
- name: Install Atom repository
  template: src=templates/atom/atom.repo dest=/etc/yum.repos.d/atom.repo
  when: install_atom
- name: Install Atom
  dnf: name=atom state=present
  when: install_atom

- name: Install Spotify repository
  get_url: url=https://negativo17.org/repos/fedora-spotify.repo dest=/etc/yum.repos.d/fedora-spotify.repo
  when: install_spotify
- name: Install Spotify
  dnf: name=spotify state=present
  when: install_spotify

- name: Install Virtualbox
  dnf: name=VirtualBox state=present
  when: install_virtualbox

- name: Install Wine
  dnf: name={{ item }} state=present
  with_items:
    - wine
    - winetricks
  when: install_wine

- name: Install n98-magerun
  get_url:
    url: https://files.magerun.net/n98-magerun.phar
    dest: "/home/{{ primary_user }}/bin/n98-magerun"
    mode: u=rwx,g=rx,o=rx
  become: true
  become_user: "{{ primary_user }}"
  when: install_magerun
- name: Install n98-magerun2
  get_url:
    url: https://files.magerun.net/n98-magerun2.phar
    dest: "/home/{{ primary_user }}/bin/n98-magerun2"
    mode: u=rwx,g=rx,o=rx
  become: true
  become_user: "{{ primary_user }}"
  when: install_magerun

- name: Include common/zsh
  include_tasks: common/zsh.yml
  tags: zsh
