---
- name: Install Node.js
  dnf:
    name: nodejs
    state: present
  become: true
  tags: node

- name: ~/.npmrc exists
  file:
    path: "{{ primary_homedir }}/.npmrc"
    state: touch

- name: ~/.npmrc prefix
  lineinfile:
    path: "{{ primary_homedir }}/.npmrc"
    regexp: '^prefix=\$\{HOME\}\/.local'
    line: 'prefix=${HOME}/.local'

- name: Install npm packages
  npm:
    name: "{{ item }}"
    state: present
    global: true
  with_items:
    - gulp
    - grunt
    - yarn
  become: true
  tags: node
